[project]
name = "adamhsparks"
r_version = "4.5"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [{ alias = "CRAN", url = "https://cloud.r-project.org/" }]

# A list of packages to install and any additional configuration
# Examples:
# "dplyr",
# {name = "dplyr", repository = "CRAN"},
# {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
  "languageserver",
  "rmarkdown",
  "knitr",
  "sf",
  "keyring",
  "weatherOz",
  "ggplot2",
  "purrr",
  "keyring",
  "data.table",
  "keyring",
  "ggiraph",
  "curl",
  "dplyr",
  "nasapower",
  "purrr",
  "epifitter",
  "blogdown",
  { name = "hrbrthemes", git = "https://github.com/hrbrmstr/hrbrthemes", branch = "master" },
  { name = "ggdark", git = "https://github.com/nsgrantham/ggdark", branch = "master" },
  { name = "httpgd", git = "https://github.com/nx10/httpgd", branch = "master" },
]
